### ISSUE TITLE
Site broken

### ISSUE THREAD

**Issue by MaxRink** [ZetaTwo/eveigbchrome#1]

**Comment by MaxRink** [comment]
https://dev.zeta-two.com/eveigb/
Gives back Error Loading Requested URL

Error Code: -112
in IGB

**Comment by ZetaTwo** [comment]
Thanks for reporting.
I will look into this as soon as possible.

**Comment by ZetaTwo** [comment]
It seems that the in-game browser doesn't accept the rather strict HTTPS settings on my server. The page is now hosted at: http://eve.zeta-two.com/igb/ and works in-game. I will update the description to reflect this.

**Comment by MaxRink** [comment]
also a desc. of how to format the hostsection would be dope

**Comment by ZetaTwo** [comment]
This is now fixed, see issue #2
